    plugins {
        id 'com.android.application'
        id 'kotlin-android'
        id 'com.google.gms.google-services'
    }

    android {
        compileSdk 34

        namespace "app.example.capriscan"

        defaultConfig {
            applicationId "app.example.capriscan"
            minSdk 23
            targetSdk 34
            versionCode 1
            versionName "1.0"

            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        }

        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            }
        }
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
        kotlinOptions {
            jvmTarget = '1.8'
        }
        buildFeatures {
            mlModelBinding true
        }
    }

    dependencies {
        implementation 'com.github.bumptech.glide:glide:4.12.0'
        implementation 'androidx.activity:activity:1.9.2'
        implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
        annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
        implementation 'androidx.core:core-ktx:1.12.0'
        implementation 'androidx.appcompat:appcompat:1.6.1'
        implementation 'com.google.android.material:material:1.10.0'
        implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

        implementation platform('com.google.firebase:firebase-bom:33.5.1')
        implementation 'com.google.firebase:firebase-analytics'
        implementation 'com.google.firebase:firebase-auth'
        implementation 'com.google.firebase:firebase-firestore'
        implementation 'com.google.firebase:firebase-storage'

        implementation 'com.google.android.gms:play-services-maps:18.1.0'
        implementation 'com.google.android.gms:play-services-location:21.0.1'
        implementation 'com.google.android.libraries.places:places:3.2.0'

        implementation 'org.tensorflow:tensorflow-lite-support:0.4.4'
        implementation 'org.tensorflow:tensorflow-lite-metadata:0.4.4'
        implementation 'androidx.activity:activity-ktx:1.8.0'
        testImplementation 'junit:junit:4.13.2'
        androidTestImplementation 'androidx.test.ext:junit:1.1.5'
        androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

        // CircleImageView for profile pictures
        implementation 'de.hdodenhof:circleimageview:3.1.0'

        // Picasso for image loading
        implementation 'com.squareup.picasso:picasso:2.8'

        // Emoji Picker
        implementation 'com.vanniktech:emoji-google:0.7.0'

        implementation 'com.squareup.okhttp3:okhttp:4.9.3'
    }